enable_language(CXX)

if (MSVC)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /bigobj /DNDEBUG /DUSE_GLOP /DUSE_BOP")
else()
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fwrapv -DNDEBUG -DUSE_GLOP -DUSE_BOP")
endif()

# Find or build Dependencies
file(READ ${CMAKE_CURRENT_SOURCE_DIR}/Dependencies.txt _Dependency_file)
foreach(DEPENDENCY Protobuf gflags glog Cbc CoinUtils Osi Clp Cgl)
    string(REGEX REPLACE ".*${DEPENDENCY} = ([0-9.]+).*" "\\1" ${DEPENDENCY}_VERSION ${_Dependency_file})
endforeach()

include(ExternalProject)

# Protobuf
find_package(Protobuf ${Protobuf_VERSION} QUIET)
if (BUILD_DEPS)
    set(Protobuf_FOUND False)
endif()
if (NOT Protobuf_FOUND)
    message(STATUS "Did not find system protobuf or forced build. Building as an external project")
    include(cmake/external/protobuf.cmake)
endif()
include_directories(${Protobuf_INCLUDE_DIRS})
set(PROTOBUF_IMPORT_DIRS ${PROJECT_SOURCE_DIR})
set(PROTOBUF_GENERATE_CPP_APPEND_PATH OFF)

# gflags
find_package(gflags ${gflags_VERSION} QUIET)
if (BUILD_DEPS)
    SET(gflags_FOUND False)
endif()
if (NOT gflags_FOUND)
    MESSAGE(STATUS "Did not find system gflags or forced build. Building as an external project")
    INCLUDE(cmake/external/gflags.cmake)
endif()
include_directories(${gflags_INCLUDE_DIRS})

# glog
find_package(glog ${glog_VERSION} QUIET)
if (BUILD_DEPS)
    SET(glog_FOUND False)
endif()
if (NOT glog_FOUND)
    MESSAGE(STATUS "Did not find system glog. Building as an external project.")
    INCLUDE(cmake/external/glog.cmake)
endif()
include_directories(${glog_INCLUDE_DIRS})

# cbc
find_package(Cbc ${Cbc_VERSION} QUIET)
if (BUILD_DEPS)
    set(Cbc_FOUND False)
endif()
if (NOT Cbc_FOUND)
    if (NOT MSVC)
        message(STATUS "Did not find system coin-cbc. Building as an external project.")
        include(cmake/external/cbc.cmake)
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DUSE_CLP -DUSE_CBC")
        include_directories(${Cbc_INCLUDE_DIRS})
    endif()
else()
    include_directories(${Cbc_INCLUDE_DIRS})
    if (MSVC)
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /DUSE_CLP /DUSE_CBC")
    else()
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DUSE_CLP -DUSE_CBC")
    endif()
ENDIF()
